"use client";

import { createContext, useContext, useState, useEffect, type ReactNode } from "react";

type Language = "en" | "hi" | "mr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    "app.name": "IndieAid",
    "app.tagline": "Helping India's stray dogs, one photo at a time",
    "app.subtitle": "AI-powered first aid guidance, emotion assessment, and rescue coordination",
    "app.footer": "SmartPaw — AI for compassion",
    "home.help": "Help a Dog",
    "home.help.desc": "Take a photo to assess condition & get first aid guidance",
    "home.nearby": "Find Help",
    "home.nearby.desc": "Vets & shelters near you",
    "home.report": "Report",
    "home.report.desc": "Log a stray needing help",
    "home.chat": "Ask IndieAid",
    "home.chat.desc": "First aid chat assistant",
    "home.learn": "Learn",
    "home.learn.desc": "Dog care & first aid guides",
    "home.emergency": "Emergency? Call now",
    "home.helpline.awbi": "AWBI Helpline",
    "home.helpline.resq": "RESQ 24x7",
    "analyze.title": "Help a Dog",
    "analyze.subtitle": "Take or upload a photo for assessment",
    "analyze.camera": "Open Camera",
    "analyze.upload": "Upload Photo",
    "analyze.upload.format": "JPEG, PNG — max 10 MB",
    "analyze.capture": "Capture",
    "analyze.analyze": "Analyze",
    "analyze.analyzing": "Analyzing...",
    "analyze.new": "Analyze Another Photo",
    "analyze.no_dog": "We couldn't detect a dog in this photo. Could you try again with a clearer image? Make sure the dog is visible and well-lit. We're here to help! 🐾",
    "analyze.error.camera": "Camera access denied. Please upload a photo instead.",
    "analyze.error.failed": "Analysis failed. Please try again.",
    "analyze.error.too_large": "Image too large. Please upload an image under 10 MB.",
    "analyze.error.invalid_format": "Please upload an image file (JPEG, PNG, WebP, GIF, BMP, TIFF, HEIC, AVIF, etc.).",
    "analyze.error.empty": "Empty file uploaded.",
    "nearby.title": "Find Help Nearby",
    "nearby.subtitle": "Vets, shelters & NGOs near you",
    "nearby.finding": "Finding help near you...",
    "nearby.empty": "No results found nearby. Try expanding your search area.",
    "nearby.search_radius": "Search radius",
    "nearby.km": "km",
    "nearby.km_away": "km away",
    "nearby.emergency_24h": "24x7 Emergency",
    "nearby.error.load": "Could not load nearby help. Please try again.",
    "nearby.filter.all": "All",
    "nearby.filter.vet": "Vets",
    "nearby.filter.shelter": "Shelters",
    "nearby.filter.ngo": "NGOs",
    "report.title": "Community Reports",
    "report.subtitle": "Stray dogs needing help near you",
    "report.form.title": "Report a Dog in Need",
    "report.form.placeholder": "Describe the dog and situation...",
    "report.form.urgency": "Urgency:",
    "report.form.photo": "Attach Photo (optional)",
    "report.form.camera": "Camera",
    "report.form.gallery": "Gallery",
    "report.form.submit": "Submit Report",
    "report.form.submitting": "Submitting...",
    "report.form.location_note": "Your current location will be attached automatically",
    "report.loading": "Loading nearby reports...",
    "report.empty": "No reports nearby yet.",
    "report.empty.cta": "Be the first to report a dog in need!",
    "report.urgency.low": "Low",
    "report.urgency.medium": "Medium",
    "report.urgency.high": "High",
    "report.urgency.critical": "Critical",
    "report.status.open": "Open",
    "report.status.in_progress": "In Progress",
    "report.status.resolved": "Resolved",
    "report.filter.all_urgency": "All urgency",
    "report.filter.all_status": "All status",
    "report.action.view_map": "View on map",
    "report.action.mark_in_progress": "Mark In-Progress",
    "report.action.mark_resolved": "Mark Resolved",
    "report.error.submit": "Failed to submit report. Please try again.",
    "report.error.update": "Failed to update status.",
    "report.prompt.resolve_note": "Add a resolution note (optional):",
    "chat.title": "SmartPaw Chat",
    "chat.subtitle": "Ask about dog first aid & care",
    "chat.welcome": "Hi, I'm SmartPaw!",
    "chat.welcome.desc": "I can help you with first aid for stray dogs, understanding dog behavior, and finding resources in Mumbai.",
    "chat.placeholder": "Ask about dog care or first aid...",
    "chat.disclaimer": "Not a vet. Always consult a professional for serious cases.",
    "chat.example.1": "How do I help a dog with mange?",
    "chat.example.2": "What should I do if I find injured puppies?",
    "chat.example.3": "Is it safe to approach a growling dog?",
    "chat.example.4": "What are the signs of rabies?",
    "chat.error.network": "I'm sorry, I'm having trouble connecting right now. For immediate help, please call the AWBI helpline at 1962.",
    "chat.action.clear": "Clear chat",
    "chat.sources": "Sources",
    "analyze.condition.title": "Condition Assessment",
    "analyze.condition.breed": "Breed",
    "analyze.condition.age": "Age",
    "analyze.condition.injuries": "Visible Injuries",
    "analyze.condition.concerns": "Health Concerns",
    "analyze.firstaid.title": "First Aid Steps",
    "analyze.loading.desc": "Let's see how we can help this pup",
    "analyze.emotion.confidence": "Confidence",
    "analyze.followup": "Ask Follow-up",
    "analyze.safety.safe": "Safe To Approach",
    "analyze.safety.caution": "Approach With Caution",
    "analyze.safety.danger": "Do Not Approach",
    "emotion.happy": "Happy",
    "emotion.sad": "Sad",
    "emotion.angry": "Angry",
    "emotion.relaxed": "Relaxed",
    "emotion.fearful": "Fearful",
    "emotion.unknown": "Unknown",
    "common.back": "←",
    "common.call": "Call",
    "common.directions": "Directions",
    "disclaimer": "Not a substitute for veterinary care. Always consult a professional.",
    "learn.subtitle": "Essential guides for helping strays",
    "learn.offline_notice": "These guides are available offline. Bookmark this page for emergencies.",
    "learn.resources_title": "Useful Resources & Links",
    "learn.emergency_title": "In an emergency, call now",
    "learn.emergency_helpline": "AWBI Helpline",
  },
  hi: {
    "app.name": "SmartPaw",
    "app.tagline": "मुंबई के आवारा कुत्तों की मदद, एक फोटो से",
    "app.subtitle": "AI-संचालित प्राथमिक चिकित्सा मार्गदर्शन और बचाव समन्वय",
    "app.footer": "SmartPaw — करुणा के लिए AI",
    "home.help": "कुत्ते की मदद करें",
    "home.help.desc": "स्थिति जांचने के लिए फोटो लें",
    "home.nearby": "मदद खोजें",
    "home.nearby.desc": "आस-पास के पशु चिकित्सक",
    "home.report": "रिपोर्ट करें",
    "home.report.desc": "मदद चाहने वाले कुत्ते की सूचना दें",
    "home.chat": "SmartPaw से पूछें",
    "home.chat.desc": "प्राथमिक चिकित्सा चैट",
    "home.learn": "सीखें",
    "home.learn.desc": "कुत्ते की देखभाल गाइड",
    "home.emergency": "आपातकाल? अभी कॉल करें",
    "home.helpline.awbi": "AWBI हेल्पलाइन",
    "home.helpline.resq": "RESQ 24x7",
    "analyze.title": "कुत्ते की मदद करें",
    "analyze.subtitle": "जांच के लिए फोटो लें या अपलोड करें",
    "analyze.camera": "कैमरा खोलें",
    "analyze.upload": "फोटो अपलोड करें",
    "analyze.upload.format": "JPEG, PNG — अधिकतम 10 MB",
    "analyze.capture": "खींचें",
    "analyze.analyze": "जांच करें",
    "analyze.analyzing": "जांच हो रही है...",
    "analyze.new": "दूसरी फोटो जांचें",
    "analyze.no_dog": "इस फोटो में हमें कुत्ता नहीं मिला। कृपया और साफ़ फोटो के साथ फिर से कोशिश करें। सुनिश्चित करें कि कुत्ता दिख रहा हो और रोशनी ठीक हो। हम मदद के लिए तैयार हैं! 🐾",
    "analyze.error.camera": "कैमरे की अनुमति नहीं मिली। कृपया फोटो अपलोड करें।",
    "analyze.error.failed": "जांच विफल हुई। कृपया फिर से कोशिश करें।",
    "analyze.error.too_large": "फोटो बहुत बड़ी है। कृपया 10 MB से छोटी फोटो अपलोड करें।",
    "analyze.error.invalid_format": "कृपया एक इमेज फ़ाइल अपलोड करें (JPEG, PNG, WebP आदि)।",
    "analyze.error.empty": "खाली फ़ाइल अपलोड हुई।",
    "nearby.title": "पास में मदद खोजें",
    "nearby.subtitle": "आस-पास के डॉक्टर और शेल्टर",
    "nearby.finding": "मदद खोज रहे हैं...",
    "nearby.empty": "पास में कोई परिणाम नहीं मिला। खोज क्षेत्र बढ़ाकर देखें।",
    "nearby.search_radius": "खोज दायरा",
    "nearby.km": "कि.मी.",
    "nearby.km_away": "कि.मी. दूर",
    "nearby.emergency_24h": "24x7 आपातकालीन",
    "nearby.error.load": "पास की मदद लोड नहीं हो सकी। कृपया फिर से कोशिश करें।",
    "nearby.filter.all": "सभी",
    "nearby.filter.vet": "पशु चिकित्सक",
    "nearby.filter.shelter": "शेल्टर",
    "nearby.filter.ngo": "NGOs",
    "report.title": "सामुदायिक रिपोर्ट",
    "report.subtitle": "आपके पास मदद चाहने वाले कुत्ते",
    "report.form.title": "ज़रूरतमंद कुत्ते की रिपोर्ट करें",
    "report.form.placeholder": "कुत्ते और स्थिति का वर्णन करें...",
    "report.form.urgency": "तात्कालिकता:",
    "report.form.photo": "फोटो लगाएं (वैकल्पिक)",
    "report.form.camera": "कैमरा",
    "report.form.gallery": "गैलरी",
    "report.form.submit": "रिपोर्ट जमा करें",
    "report.form.submitting": "जमा हो रही है...",
    "report.form.location_note": "आपका वर्तमान स्थान अपने आप जुड़ जाएगा",
    "report.loading": "रिपोर्ट लोड हो रहीं हैं...",
    "report.empty": "पास में कोई रिपोर्ट नहीं।",
    "report.empty.cta": "पहली रिपोर्ट दर्ज करें!",
    "report.urgency.low": "कम",
    "report.urgency.medium": "मध्यम",
    "report.urgency.high": "ज़्यादा",
    "report.urgency.critical": "गंभीर",
    "report.status.open": "खुला",
    "report.status.in_progress": "प्रगति पर",
    "report.status.resolved": "हल हो गया",
    "report.filter.all_urgency": "सभी तात्कालिकता",
    "report.filter.all_status": "सभी स्थितियां",
    "report.action.view_map": "मानचित्र पर देखें",
    "report.action.mark_in_progress": "प्रगति पर चिह्नित करें",
    "report.action.mark_resolved": "हल हुआ चिह्नित करें",
    "report.error.submit": "रिपोर्ट जमा नहीं हो सकी। कृपया फिर से कोशिश करें।",
    "report.error.update": "स्थिति अपडेट नहीं हो सकी।",
    "report.prompt.resolve_note": "समाधान नोट जोड़ें (वैकल्पिक):",
    "chat.title": "SmartPaw चैट",
    "chat.subtitle": "कुत्ते की देखभाल के बारे में पूछें",
    "chat.welcome": "नमस्ते, मैं SmartPaw हूं!",
    "chat.welcome.desc": "मैं आवारा कुत्तों की प्राथमिक चिकित्सा, व्यवहार समझने और मुंबई में संसाधन खोजने में मदद कर सकता हूं।",
    "chat.placeholder": "कुत्ते की देखभाल के बारे में पूछें...",
    "chat.disclaimer": "पशु चिकित्सक नहीं। गंभीर मामलों में हमेशा पेशेवर से सलाह लें।",
    "chat.example.1": "मांगे वाले कुत्ते की मदद कैसे करूं?",
    "chat.example.2": "घायल पिल्ले मिलें तो क्या करूं?",
    "chat.example.3": "गुर्राने वाले कुत्ते के पास जाना सुरक्षित है?",
    "chat.example.4": "रेबीज के लक्षण क्या हैं?",
    "chat.error.network": "क्षमा करें, अभी कनेक्ट नहीं हो पा रहा। तुरंत मदद के लिए AWBI हेल्पलाइन 1962 पर कॉल करें।",
    "chat.action.clear": "चैट साफ़ करें",
    "chat.sources": "स्रोत",
    "analyze.condition.title": "स्थिति मूल्यांकन",
    "analyze.condition.breed": "नस्ल",
    "analyze.condition.age": "उम्र",
    "analyze.condition.injuries": "दिखाई देने वाली चोटें",
    "analyze.condition.concerns": "स्वास्थ्य संबंधी चिंताएं",
    "analyze.firstaid.title": "प्राथमिक चिकित्सा के कदम",
    "analyze.loading.desc": "देखते हैं इस कुत्ते की कैसे मदद करें",
    "analyze.emotion.confidence": "विश्वसनीयता",
    "analyze.followup": "आगे पूछें",
    "analyze.safety.safe": "पास जाना सुरक्षित है",
    "analyze.safety.caution": "सावधानी से पास जाएं",
    "analyze.safety.danger": "पास न जाएं",
    "emotion.happy": "खुश",
    "emotion.sad": "दुखी",
    "emotion.angry": "गुस्से में",
    "emotion.relaxed": "शांत",
    "emotion.fearful": "डरा हुआ",
    "emotion.unknown": "अज्ञात",
    "common.back": "←",
    "common.call": "कॉल",
    "common.directions": "दिशानिर्देश",
    "disclaimer": "यह पशु चिकित्सा का विकल्प नहीं है। हमेशा पेशेवर से परामर्श करें।",
    "learn.subtitle": "आवारा कुत्तों की मदद के लिए ज़रूरी गाइड",
    "learn.offline_notice": "ये गाइड ऑफलाइन भी उपलब्ध हैं। आपातकाल के लिए इस पेज को बुकमार्क करें।",
    "learn.resources_title": "उपयोगी संसाधन और लिंक",
    "learn.emergency_title": "आपातकाल में, अभी कॉल करें",
    "learn.emergency_helpline": "AWBI हेल्पलाइन",
  },
  mr: {
    "app.name": "SmartPaw",
    "app.tagline": "मुंबईच्या भटक्या कुत्र्यांना मदत, एका फोटोतून",
    "app.subtitle": "AI-चालित प्रथमोपचार मार्गदर्शन आणि बचाव समन्वय",
    "app.footer": "SmartPaw — करुणेसाठी AI",
    "home.help": "कुत्र्याला मदत करा",
    "home.help.desc": "स्थिती तपासण्यासाठी फोटो काढा",
    "home.nearby": "मदत शोधा",
    "home.nearby.desc": "जवळचे पशुवैद्य",
    "home.report": "कळवा",
    "home.report.desc": "मदत हव्या असलेल्या कुत्र्याची माहिती द्या",
    "home.chat": "SmartPaw ला विचारा",
    "home.chat.desc": "प्रथमोपचार चॅट",
    "home.learn": "शिका",
    "home.learn.desc": "कुत्र्यांची काळजी मार्गदर्शक",
    "home.emergency": "आणीबाणी? आत्ता कॉल करा",
    "home.helpline.awbi": "AWBI हेल्पलाइन",
    "home.helpline.resq": "RESQ 24x7",
    "analyze.title": "कुत्र्याला मदत करा",
    "analyze.subtitle": "तपासणीसाठी फोटो काढा किंवा अपलोड करा",
    "analyze.camera": "कॅमेरा उघडा",
    "analyze.upload": "फोटो अपलोड करा",
    "analyze.upload.format": "JPEG, PNG — कमाल 10 MB",
    "analyze.capture": "टिपा",
    "analyze.analyze": "तपासा",
    "analyze.analyzing": "तपासणी सुरू...",
    "analyze.new": "दुसरा फोटो तपासा",
    "analyze.no_dog": "या फोटोत आम्हाला कुत्रा सापडला नाही. कृपया अधिक स्पष्ट फोटोसह पुन्हा प्रयत्न करा. कुत्रा दिसत असल्याची आणि प्रकाश पुरेसा असल्याची खात्री करा. आम्ही मदतीसाठी तयार आहोत! 🐾",
    "analyze.error.camera": "कॅमेरा वापरण्याची परवानगी नाकारली. कृपया फोटो अपलोड करा.",
    "analyze.error.failed": "तपासणी अयशस्वी. कृपया पुन्हा प्रयत्न करा.",
    "analyze.error.too_large": "फोटो खूप मोठा आहे. कृपया 10 MB पेक्षा लहान फोटो अपलोड करा.",
    "analyze.error.invalid_format": "कृपया एक प्रतिमा फाइल अपलोड करा (JPEG, PNG, WebP इ.).",
    "analyze.error.empty": "रिकामी फाइल अपलोड झाली.",
    "nearby.title": "जवळ मदत शोधा",
    "nearby.subtitle": "जवळचे डॉक्टर आणि शेल्टर",
    "nearby.finding": "मदत शोधत आहे...",
    "nearby.empty": "जवळ काही आढळले नाही. शोध परिसर वाढवून पहा.",
    "nearby.search_radius": "शोध परिसर",
    "nearby.km": "कि.मी.",
    "nearby.km_away": "कि.मी. दूर",
    "nearby.emergency_24h": "24x7 आणीबाणी",
    "nearby.error.load": "जवळची मदत लोड होऊ शकली नाही. कृपया पुन्हा प्रयत्न करा.",
    "nearby.filter.all": "सर्व",
    "nearby.filter.vet": "पशुवैद्य",
    "nearby.filter.shelter": "शेल्टर",
    "nearby.filter.ngo": "NGOs",
    "report.title": "समुदाय अहवाल",
    "report.subtitle": "तुमच्या जवळ मदत हव्या असलेले कुत्रे",
    "report.form.title": "गरजू कुत्र्याचा अहवाल द्या",
    "report.form.placeholder": "कुत्रा आणि परिस्थितीचे वर्णन करा...",
    "report.form.urgency": "तातडी:",
    "report.form.photo": "फोटो जोडा (पर्यायी)",
    "report.form.camera": "कॅमेरा",
    "report.form.gallery": "गॅलरी",
    "report.form.submit": "अहवाल सादर करा",
    "report.form.submitting": "सादर होत आहे...",
    "report.form.location_note": "तुमचे सध्याचे स्थान आपोआप जोडले जाईल",
    "report.loading": "अहवाल लोड होत आहेत...",
    "report.empty": "जवळ अहवाल नाहीत.",
    "report.empty.cta": "पहिला अहवाल नोंदवा!",
    "report.urgency.low": "कमी",
    "report.urgency.medium": "मध्यम",
    "report.urgency.high": "जास्त",
    "report.urgency.critical": "गंभीर",
    "report.status.open": "उघडा",
    "report.status.in_progress": "प्रगतीत",
    "report.status.resolved": "सुटलेला",
    "report.filter.all_urgency": "सर्व तातडी",
    "report.filter.all_status": "सर्व स्थिती",
    "report.action.view_map": "नकाशावर पहा",
    "report.action.mark_in_progress": "प्रगतीत म्हणून चिन्हांकित करा",
    "report.action.mark_resolved": "सुटले म्हणून चिन्हांकित करा",
    "report.error.submit": "अहवाल सादर करता आला नाही. कृपया पुन्हा प्रयत्न करा.",
    "report.error.update": "स्थिती अद्यतनित करता आली नाही.",
    "report.prompt.resolve_note": "निराकरण नोट जोडा (पर्यायी):",
    "chat.title": "SmartPaw चॅट",
    "chat.subtitle": "कुत्र्यांच्या काळजीबद्दल विचारा",
    "chat.welcome": "नमस्कार, मी SmartPaw आहे!",
    "chat.welcome.desc": "मी भटक्या कुत्र्यांसाठी प्रथमोपचार, वर्तन समजून घेणे आणि मुंबईत संसाधने शोधण्यात मदत करू शकतो.",
    "chat.placeholder": "कुत्र्यांच्या काळजीबद्दल विचारा...",
    "chat.disclaimer": "पशुवैद्य नाही. गंभीर प्रकरणांसाठी नेहमी व्यावसायिकांचा सल्ला घ्या.",
    "chat.example.1": "खरजेच्या कुत्र्याला कशी मदत करावी?",
    "chat.example.2": "जखमी पिल्ले आढळल्यास काय करावे?",
    "chat.example.3": "गुरगुरणाऱ्या कुत्र्याजवळ जाणे सुरक्षित आहे का?",
    "chat.example.4": "रेबीजची लक्षणे काय आहेत?",
    "chat.error.network": "क्षमस्व, सध्या कनेक्ट होऊ शकत नाही. त्वरित मदतीसाठी AWBI हेल्पलाइन 1962 वर कॉल करा.",
    "chat.action.clear": "चॅट साफ करा",
    "chat.sources": "स्रोत",
    "analyze.condition.title": "स्थिती मूल्यमापन",
    "analyze.condition.breed": "जात",
    "analyze.condition.age": "वय",
    "analyze.condition.injuries": "दिसणाऱ्या जखमा",
    "analyze.condition.concerns": "आरोग्य समस्या",
    "analyze.firstaid.title": "प्रथमोपचाराचे टप्पे",
    "analyze.loading.desc": "पाहूया या कुत्र्याला कशी मदत करता येईल",
    "analyze.emotion.confidence": "विश्वासार्हता",
    "analyze.followup": "पुढे विचारा",
    "analyze.safety.safe": "जवळ जाणे सुरक्षित",
    "analyze.safety.caution": "सावधगिरीने जवळ जा",
    "analyze.safety.danger": "जवळ जाऊ नका",
    "emotion.happy": "आनंदी",
    "emotion.sad": "दुःखी",
    "emotion.angry": "रागावलेला",
    "emotion.relaxed": "शांत",
    "emotion.fearful": "घाबरलेला",
    "emotion.unknown": "अज्ञात",
    "common.back": "←",
    "common.call": "कॉल",
    "common.directions": "दिशानिर्देश",
    "disclaimer": "हे पशुवैद्यकीय काळजीचा पर्याय नाही. नेहमी व्यावसायिकांचा सल्ला घ्या.",
    "learn.subtitle": "भटक्या कुत्र्यांना मदत करण्यासाठी आवश्यक मार्गदर्शक",
    "learn.offline_notice": "हे मार्गदर्शक ऑफलाइन उपलब्ध आहेत. आणीबाणीसाठी हे पेज बुकमार्क करा.",
    "learn.resources_title": "उपयुक्त संसाधने आणि दुवे",
    "learn.emergency_title": "आणीबाणीत, आत्ता कॉल करा",
    "learn.emergency_helpline": "AWBI हेल्पलाइन",
  },
};

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLang] = useState<Language>("en");

  useEffect(() => {
    const saved = localStorage.getItem("smartpaw-lang") as Language | null;
    if (saved && (saved === "en" || saved === "hi" || saved === "mr")) {
      setLang(saved);
    }
  }, []);

  // Keep <html lang> in sync for accessibility & SEO
  useEffect(() => {
    if (typeof document !== "undefined") {
      document.documentElement.lang = language;
    }
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLang(lang);
    localStorage.setItem("smartpaw-lang", lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}

export function LanguageSelector({ compact = false }: { compact?: boolean }) {
  const { language, setLanguage } = useLanguage();
  const options = [
    { code: "en" as Language, label: compact ? "EN" : "English" },
    { code: "hi" as Language, label: compact ? "हि" : "हिन्दी" },
    { code: "mr" as Language, label: compact ? "म" : "मराठी" },
  ];

  return (
    <div className="flex gap-1.5">
      {options.map((o) => (
        <button
          key={o.code}
          onClick={() => setLanguage(o.code)}
          className={`px-3 py-1 rounded-full text-sm font-medium transition-colors ${
            language === o.code
              ? "bg-[var(--color-warm-500)] text-white"
              : "bg-gray-100 text-gray-500 hover:bg-gray-200"
          }`}
        >
          {o.label}
        </button>
      ))}
    </div>
  );
}
